
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 31 06:27:48 IST 2015
//----------------------------------------------------

package compiler;

/** CUP generated interface containing symbol constants. */
public interface ICSym {
  /* terminals */
  public static final int DIVIDE = 4;
  public static final int LCBR = 14;
  public static final int LTE = 35;
  public static final int UMINUS = 49;
  public static final int INTEGER = 47;
  public static final int SEMI = 36;
  public static final int CONTINUE = 15;
  public static final int INT = 9;
  public static final int MINUS = 23;
  public static final int STATIC = 43;
  public static final int LT = 21;
  public static final int LP = 5;
  public static final int COMMA = 44;
  public static final int CLASS = 22;
  public static final int RP = 6;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 3;
  public static final int ASSIGN = 7;
  public static final int QUOTE = 11;
  public static final int IF = 32;
  public static final int THIS = 12;
  public static final int ID = 48;
  public static final int DOT = 31;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int RCBR = 25;
  public static final int LB = 33;
  public static final int LAND = 20;
  public static final int EQUAL = 29;
  public static final int TRUE = 24;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int RB = 34;
  public static final int LOR = 19;
  public static final int NULL = 8;
  public static final int MOD = 46;
  public static final int BREAK = 40;
  public static final int VOID = 10;
  public static final int GTE = 38;
  public static final int ELSE = 45;
  public static final int WHILE = 26;
  public static final int NEQUAL = 17;
  public static final int CLASS_ID = 13;
  public static final int EXTENDS = 30;
  public static final int STRING = 18;
  public static final int LNEG = 28;
  public static final int FALSE = 27;
  public static final int GT = 41;
  public static final int LENGTH = 42;
}

